dist: bionic
language: ruby
cache: bundler

rvm:
  - ruby-head
  - 2.7.0
  - 2.6.5
  - 2.5.7
  - 2.4.9
  - 2.3.8

before_install: gem install bundler -v 2.1.4

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
