---
language: ruby
cache: bundler
rvm:
  - ruby-head
  - 2.6.4
  - 2.5.6
  - 2.4.7
  - 2.3.8
before_install: gem install bundler -v 2.0.2

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
